import type { AlgorithmDef } from "./types.js";

const CATEGORIES: { name: string; algorithms: Omit<AlgorithmDef, "category">[] }[] = [
  { name: "Maze", algorithms: [
    { id: 10, name: "Maze (DFS)", params: [
      { name: "room_chance", min: 0, max: 0.5, default: 0.15, step: 0.05 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 9, default: 5, step: 1 },
    ]},
    { id: 21, name: "Eller's Maze", params: [
      { name: "merge_chance", min: 0.1, max: 0.9, default: 0.5, step: 0.05 },
      { name: "room_chance", min: 0, max: 0.5, default: 0.12, step: 0.02 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 9, default: 5, step: 1 },
    ]},
    { id: 24, name: "Kruskal's Maze", params: [
      { name: "room_chance", min: 0, max: 0.5, default: 0.12, step: 0.02 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 9, default: 5, step: 1 },
    ]},
    { id: 26, name: "Binary Tree Maze", params: [
      { name: "room_chance", min: 0, max: 0.5, default: 0.12, step: 0.02 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 9, default: 5, step: 1 },
    ]},
    { id: 27, name: "Sidewinder Maze", params: [
      { name: "carve_chance", min: 0.1, max: 0.9, default: 0.5, step: 0.05 },
      { name: "room_chance", min: 0, max: 0.5, default: 0.12, step: 0.02 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 9, default: 5, step: 1 },
    ]},
    { id: 25, name: "Recursive Division", params: [
      { name: "min_room_size", min: 2, max: 8, default: 3, step: 1 },
      { name: "room_chance", min: 0, max: 0.5, default: 0.1, step: 0.05 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 9, default: 5, step: 1 },
    ]},
    { id: 32, name: "Growing Tree", params: [
      { name: "newest_weight", min: 0, max: 1, default: 1.0, step: 0.05 },
      { name: "room_chance", min: 0, max: 0.5, default: 0.12, step: 0.02 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 9, default: 5, step: 1 },
    ]},
    { id: 33, name: "Wilson's", params: [
      { name: "room_chance", min: 0, max: 0.5, default: 0.12, step: 0.02 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 9, default: 5, step: 1 },
    ]},
    { id: 34, name: "Aldous-Broder", params: [
      { name: "room_chance", min: 0, max: 0.5, default: 0.12, step: 0.02 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 9, default: 5, step: 1 },
    ]},
    { id: 35, name: "Hunt and Kill", params: [
      { name: "room_chance", min: 0, max: 0.5, default: 0.12, step: 0.02 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 9, default: 5, step: 1 },
    ]},
    { id: 53, name: "Pac-Man Maze", params: [
      { name: "wall_density", min: 0.1, max: 0.6, default: 0.3, step: 0.05 },
      { name: "corridor_width", min: 1, max: 4, default: 2, step: 1 },
      { name: "chamber_size", min: 3, max: 9, default: 5, step: 1 },
      { name: "symmetry", min: 0, max: 1, default: 0, step: 1 },
    ]},
  ]},
  { name: "Room", algorithms: [
    { id: 2, name: "BSP Tree", params: [
      { name: "min_room_size", min: 2, max: 10, default: 4, step: 1 },
      { name: "max_depth", min: 1, max: 8, default: 4, step: 1 },
    ]},
    { id: 3, name: "Poisson Disk", params: [
      { name: "min_distance", min: 3, max: 15, default: 8, step: 1 },
      { name: "room_min_size", min: 2, max: 8, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 12, default: 6, step: 1 },
      { name: "max_attempts", min: 5, max: 100, default: 30, step: 5 },
    ]},
    { id: 11, name: "Rooms and Mazes", params: [
      { name: "num_room_attempts", min: 10, max: 200, default: 50, step: 10 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 12, default: 7, step: 1 },
      { name: "winding_chance", min: 0, max: 1, default: 0.3, step: 0.05 },
      { name: "extra_connector_chance", min: 0, max: 0.2, default: 0.02, step: 0.01 },
    ]},
    { id: 15, name: "Rogue Classic", params: [
      { name: "grid_cols", min: 2, max: 5, default: 3, step: 1 },
      { name: "grid_rows", min: 2, max: 5, default: 3, step: 1 },
      { name: "room_min_ratio", min: 0.2, max: 0.8, default: 0.4, step: 0.05 },
      { name: "room_max_ratio", min: 0.3, max: 1, default: 0.8, step: 0.05 },
      { name: "skip_chance", min: 0, max: 0.5, default: 0.15, step: 0.05 },
    ]},
    { id: 16, name: "Room Accretion", params: [
      { name: "max_rooms", min: 3, max: 30, default: 12, step: 1 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 4, max: 15, default: 8, step: 1 },
      { name: "max_attempts_per_room", min: 20, max: 500, default: 100, step: 20 },
      { name: "first_room_size", min: 3, max: 12, default: 6, step: 1 },
    ]},
    { id: 17, name: "TinyKeep", params: [
      { name: "num_rooms", min: 5, max: 60, default: 30, step: 5 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 4, max: 15, default: 9, step: 1 },
      { name: "main_room_threshold", min: 3, max: 10, default: 5, step: 1 },
      { name: "extra_edge_chance", min: 0, max: 0.5, default: 0.15, step: 0.05 },
      { name: "separation_iterations", min: 10, max: 200, default: 50, step: 10 },
    ]},
    { id: 18, name: "Feature Growing", params: [
      { name: "max_features", min: 5, max: 80, default: 30, step: 5 },
      { name: "max_attempts", min: 50, max: 2000, default: 500, step: 50 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 12, default: 7, step: 1 },
      { name: "corridor_min_len", min: 1, max: 8, default: 3, step: 1 },
      { name: "corridor_max_len", min: 3, max: 15, default: 8, step: 1 },
      { name: "room_weight", min: 1, max: 10, default: 3, step: 1 },
      { name: "corridor_weight", min: 1, max: 10, default: 5, step: 1 },
    ]},
    { id: 23, name: "BFS Room Expansion", params: [
      { name: "num_seeds", min: 3, max: 20, default: 10, step: 1 },
      { name: "min_room_size", min: 4, max: 20, default: 8, step: 1 },
      { name: "parallel_steps", min: 4, max: 30, default: 12, step: 1 },
      { name: "serial_steps", min: 5, max: 50, default: 20, step: 1 },
      { name: "door_chance", min: 0, max: 1, default: 0.8, step: 0.05 },
      { name: "extra_door_chance", min: 0, max: 0.5, default: 0.15, step: 0.05 },
    ]},
    { id: 31, name: "Prefab Assembly", params: [
      { name: "num_prefabs", min: 3, max: 30, default: 12, step: 1 },
      { name: "max_attempts", min: 20, max: 500, default: 100, step: 20 },
    ]},
    { id: 47, name: "Gravity Collapse", params: [
      { name: "num_rooms", min: 3, max: 25, default: 12, step: 1 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 4, max: 12, default: 7, step: 1 },
      { name: "corridor_width", min: 1, max: 3, default: 1, step: 1 },
      { name: "gap", min: 0, max: 3, default: 0, step: 1 },
    ]},
    { id: 54, name: "Tetromino Packing", params: [
      { name: "max_attempts", min: 50, max: 500, default: 200, step: 50 },
      { name: "connect_adjacent", min: 0, max: 1, default: 1, step: 1 },
      { name: "corridor_width", min: 1, max: 3, default: 1, step: 1 },
    ]},
  ]},
  { name: "Cave", algorithms: [
    { id: 1, name: "Cellular Automata", params: [
      { name: "initial_fill", min: 0.1, max: 0.9, default: 0.45, step: 0.05 },
      { name: "iterations", min: 1, max: 20, default: 5, step: 1 },
      { name: "birth_threshold", min: 1, max: 8, default: 5, step: 1 },
      { name: "survival_threshold", min: 1, max: 8, default: 4, step: 1 },
    ]},
    { id: 0, name: "Drunkard's Walk", params: [
      { name: "fill_ratio", min: 0.1, max: 0.8, default: 0.4, step: 0.05 },
      { name: "max_steps", min: 500, max: 20000, default: 5000, step: 500 },
    ]},
    { id: 19, name: "Noise Caves", params: [
      { name: "threshold", min: 0.1, max: 0.9, default: 0.45, step: 0.05 },
      { name: "octaves", min: 1, max: 8, default: 4, step: 1 },
      { name: "scale", min: 0.01, max: 0.3, default: 0.08, step: 0.01 },
      { name: "persistence", min: 0.1, max: 0.9, default: 0.5, step: 0.05 },
    ]},
    { id: 13, name: "DLA", params: [
      { name: "target_fill", min: 0.1, max: 0.6, default: 0.35, step: 0.05 },
      { name: "max_walk_steps", min: 100, max: 2000, default: 500, step: 100 },
      { name: "num_seeds", min: 1, max: 10, default: 3, step: 1 },
    ]},
    { id: 44, name: "Marching Squares", params: [
      { name: "initial_fill", min: 0.1, max: 0.9, default: 0.45, step: 0.05 },
      { name: "ca_iterations", min: 1, max: 20, default: 5, step: 1 },
      { name: "birth_threshold", min: 1, max: 8, default: 5, step: 1 },
      { name: "survival_threshold", min: 1, max: 8, default: 4, step: 1 },
      { name: "smooth", min: 0, max: 1, default: 1, step: 1 },
    ]},
    { id: 14, name: "Worm Tunnels", params: [
      { name: "num_worms", min: 1, max: 10, default: 4, step: 1 },
      { name: "worm_length", min: 10, max: 200, default: 60, step: 10 },
      { name: "worm_min_width", min: 1, max: 3, default: 1, step: 1 },
      { name: "worm_max_width", min: 1, max: 6, default: 3, step: 1 },
      { name: "turn_chance", min: 0, max: 1, default: 0.3, step: 0.05 },
      { name: "room_chance", min: 0, max: 0.3, default: 0.08, step: 0.02 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 8, default: 5, step: 1 },
    ]},
    { id: 36, name: "Erosion", params: [
      { name: "num_drops", min: 100, max: 2000, default: 500, step: 100 },
      { name: "erosion_strength", min: 0.01, max: 0.5, default: 0.1, step: 0.01 },
      { name: "deposition_rate", min: 0.01, max: 0.3, default: 0.05, step: 0.01 },
      { name: "threshold", min: 0.1, max: 0.9, default: 0.45, step: 0.05 },
    ]},
    { id: 46, name: "Percolation", params: [
      { name: "open_chance", min: 0.3, max: 0.8, default: 0.55, step: 0.05 },
      { name: "widen", min: 0, max: 3, default: 1, step: 1 },
      { name: "min_component_size", min: 1, max: 50, default: 10, step: 1 },
    ]},
    { id: 45, name: "Ant Colony", params: [
      { name: "num_ants", min: 2, max: 30, default: 10, step: 1 },
      { name: "steps_per_ant", min: 50, max: 500, default: 200, step: 50 },
      { name: "pheromone_strength", min: 0.1, max: 3.0, default: 1.0, step: 0.1 },
      { name: "evaporation_rate", min: 0.01, max: 0.5, default: 0.1, step: 0.01 },
      { name: "room_chance", min: 0, max: 0.5, default: 0.1, step: 0.05 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 9, default: 5, step: 1 },
    ]},
    { id: 57, name: "Worley Noise", params: [
      { name: "num_points", min: 5, max: 50, default: 20, step: 1 },
      { name: "threshold", min: 0.1, max: 0.8, default: 0.3, step: 0.05 },
      { name: "use_manhattan", min: 0, max: 1, default: 1, step: 1 },
    ]},
    { id: 58, name: "Ridged Multifractal", params: [
      { name: "octaves", min: 1, max: 8, default: 4, step: 1 },
      { name: "scale", min: 0.01, max: 0.2, default: 0.06, step: 0.01 },
      { name: "persistence", min: 0.1, max: 0.9, default: 0.5, step: 0.05 },
      { name: "lacunarity", min: 1, max: 4, default: 2.0, step: 0.1 },
      { name: "threshold", min: 0.1, max: 0.9, default: 0.5, step: 0.05 },
      { name: "sharpness", min: 0.5, max: 5, default: 2.0, step: 0.1 },
    ]},
    { id: 59, name: "Domain Warping", params: [
      { name: "scale", min: 0.01, max: 0.2, default: 0.08, step: 0.01 },
      { name: "warp_strength", min: 0.5, max: 10, default: 4.0, step: 0.5 },
      { name: "warp_iterations", min: 1, max: 5, default: 2, step: 1 },
      { name: "threshold", min: 0.1, max: 0.9, default: 0.45, step: 0.05 },
      { name: "octaves", min: 1, max: 8, default: 3, step: 1 },
    ]},
    { id: 60, name: "Reaction-Diffusion", params: [
      { name: "iterations", min: 500, max: 5000, default: 3000, step: 500 },
      { name: "du", min: 0.1, max: 2, default: 1.0, step: 0.1 },
      { name: "dv", min: 0.1, max: 1, default: 0.5, step: 0.05 },
      { name: "feed", min: 0.01, max: 0.1, default: 0.055, step: 0.005 },
      { name: "kill", min: 0.01, max: 0.1, default: 0.062, step: 0.005 },
      { name: "threshold", min: 0.05, max: 0.5, default: 0.2, step: 0.05 },
      { name: "dt", min: 0.1, max: 2, default: 1.0, step: 0.1 },
    ]},
    { id: 63, name: "Slime Mold", params: [
      { name: "num_agents", min: 50, max: 500, default: 200, step: 50 },
      { name: "num_food", min: 1, max: 15, default: 5, step: 1 },
      { name: "steps", min: 100, max: 1000, default: 300, step: 50 },
      { name: "sensor_angle", min: 1, max: 4, default: 1, step: 1 },
      { name: "sensor_distance", min: 1, max: 8, default: 3, step: 1 },
      { name: "deposit_amount", min: 0.1, max: 3, default: 1.0, step: 0.1 },
      { name: "decay_rate", min: 0.01, max: 0.5, default: 0.1, step: 0.01 },
      { name: "threshold", min: 0.1, max: 0.9, default: 0.5, step: 0.05 },
    ]},
    { id: 64, name: "Lightning", params: [
      { name: "num_bolts", min: 1, max: 8, default: 3, step: 1 },
      { name: "branch_chance", min: 0, max: 0.8, default: 0.3, step: 0.05 },
      { name: "max_steps", min: 100, max: 1000, default: 500, step: 50 },
      { name: "room_chance", min: 0, max: 0.5, default: 0.15, step: 0.05 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 8, default: 5, step: 1 },
    ]},
  ]},
  { name: "Graph", algorithms: [
    { id: 4, name: "Graph Grammar", params: [
      { name: "num_rooms", min: 3, max: 15, default: 6, step: 1 },
      { name: "num_locks", min: 0, max: 5, default: 2, step: 1 },
      { name: "room_size", min: 3, max: 8, default: 4, step: 1 },
    ]},
    { id: 6, name: "Diablo", params: [
      { name: "spine_length", min: 2, max: 12, default: 6, step: 1 },
      { name: "branch_chance", min: 0, max: 1, default: 0.5, step: 0.05 },
      { name: "loop_chance", min: 0, max: 1, default: 0.25, step: 0.05 },
      { name: "room_min_size", min: 2, max: 8, default: 3, step: 1 },
      { name: "room_max_size", min: 4, max: 15, default: 9, step: 1 },
      { name: "room_padding", min: 0, max: 5, default: 2, step: 1 },
      { name: "max_placement_attempts", min: 10, max: 200, default: 50, step: 10 },
    ]},
    { id: 7, name: "Spelunky", params: [
      { name: "grid_cols", min: 2, max: 8, default: 4, step: 1 },
      { name: "grid_rows", min: 2, max: 8, default: 4, step: 1 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 8, default: 5, step: 1 },
      { name: "off_path_chance", min: 0, max: 1, default: 0.3, step: 0.05 },
    ]},
    { id: 8, name: "Arena Chain", params: [
      { name: "num_arenas", min: 2, max: 10, default: 5, step: 1 },
      { name: "arena_min_size", min: 5, max: 15, default: 7, step: 1 },
      { name: "arena_max_size", min: 7, max: 25, default: 13, step: 1 },
      { name: "corridor_width", min: 1, max: 5, default: 2, step: 1 },
      { name: "side_room_chance", min: 0, max: 1, default: 0.4, step: 0.05 },
      { name: "side_room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "side_room_max_size", min: 3, max: 8, default: 5, step: 1 },
      { name: "max_placement_attempts", min: 10, max: 200, default: 50, step: 10 },
    ]},
    { id: 39, name: "Cyclic Dungeon", params: [
      { name: "num_rooms", min: 3, max: 15, default: 8, step: 1 },
      { name: "num_keys", min: 0, max: 5, default: 2, step: 1 },
      { name: "cycle_chance", min: 0, max: 1, default: 0.3, step: 0.05 },
      { name: "room_min_size", min: 3, max: 8, default: 4, step: 1 },
      { name: "room_max_size", min: 4, max: 12, default: 7, step: 1 },
    ]},
    { id: 40, name: "Metroidvania", params: [
      { name: "num_zones", min: 2, max: 8, default: 4, step: 1 },
      { name: "rooms_per_zone", min: 2, max: 8, default: 4, step: 1 },
      { name: "gate_chance", min: 0, max: 1, default: 0.3, step: 0.05 },
      { name: "room_min_size", min: 3, max: 8, default: 4, step: 1 },
      { name: "room_max_size", min: 4, max: 12, default: 8, step: 1 },
    ]},
    { id: 41, name: "Mission Graph", params: [
      { name: "num_nodes", min: 4, max: 20, default: 10, step: 1 },
      { name: "branch_chance", min: 0, max: 1, default: 0.3, step: 0.05 },
      { name: "lock_chance", min: 0, max: 1, default: 0.2, step: 0.05 },
      { name: "room_min_size", min: 3, max: 8, default: 4, step: 1 },
      { name: "room_max_size", min: 4, max: 12, default: 7, step: 1 },
    ]},
    { id: 52, name: "Ring Dungeon", params: [
      { name: "ring_padding", min: 2, max: 8, default: 4, step: 1 },
      { name: "num_rooms", min: 3, max: 15, default: 8, step: 1 },
      { name: "room_min_size", min: 3, max: 8, default: 4, step: 1 },
      { name: "room_max_size", min: 4, max: 12, default: 7, step: 1 },
      { name: "num_shortcuts", min: 0, max: 5, default: 2, step: 1 },
      { name: "shortcut_width", min: 1, max: 3, default: 1, step: 1 },
    ]},
    { id: 65, name: "Binding of Isaac", params: [
      { name: "room_size", min: 5, max: 15, default: 9, step: 2 },
      { name: "num_rooms", min: 5, max: 25, default: 12, step: 1 },
      { name: "min_rooms", min: 3, max: 15, default: 8, step: 1 },
      { name: "max_dead_ends", min: 1, max: 8, default: 4, step: 1 },
    ]},
    { id: 66, name: "Dead Cells", params: [
      { name: "path_length", min: 3, max: 10, default: 5, step: 1 },
      { name: "max_branches", min: 1, max: 6, default: 3, step: 1 },
      { name: "branch_chance", min: 0.1, max: 0.8, default: 0.4, step: 0.05 },
      { name: "shortcut_chance", min: 0, max: 0.5, default: 0.2, step: 0.05 },
      { name: "biome_min_size", min: 3, max: 10, default: 6, step: 1 },
      { name: "biome_max_size", min: 5, max: 15, default: 10, step: 1 },
    ]},
  ]},
  { name: "Curve", algorithms: [
    { id: 30, name: "Hilbert Curve", params: [
      { name: "order", min: 1, max: 6, default: 4, step: 1 },
      { name: "corridor_width", min: 1, max: 4, default: 1, step: 1 },
      { name: "room_chance", min: 0, max: 0.3, default: 0.08, step: 0.02 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 8, default: 5, step: 1 },
    ]},
    { id: 50, name: "Gosper Curve", params: [
      { name: "order", min: 1, max: 5, default: 3, step: 1 },
      { name: "corridor_width", min: 1, max: 3, default: 1, step: 1 },
      { name: "room_chance", min: 0, max: 0.3, default: 0.1, step: 0.05 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 8, default: 5, step: 1 },
    ]},
    { id: 49, name: "Spiral", params: [
      { name: "spacing", min: 1, max: 6, default: 3, step: 1 },
      { name: "corridor_width", min: 1, max: 3, default: 1, step: 1 },
      { name: "room_chance", min: 0, max: 0.5, default: 0.2, step: 0.05 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 8, default: 5, step: 1 },
      { name: "num_turns", min: 1, max: 10, default: 5, step: 1 },
    ]},
    { id: 48, name: "Sierpinski Dungeon", params: [
      { name: "depth", min: 1, max: 5, default: 3, step: 1 },
      { name: "corridor_width", min: 1, max: 3, default: 1, step: 1 },
      { name: "room_chance", min: 0, max: 0.3, default: 0.1, step: 0.05 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 8, default: 5, step: 1 },
    ]},
  ]},
  { name: "Terrain", algorithms: [
    { id: 28, name: "Diamond-Square", params: [
      { name: "roughness", min: 0.1, max: 1.5, default: 0.6, step: 0.05 },
      { name: "threshold", min: 0.1, max: 0.9, default: 0.45, step: 0.05 },
      { name: "initial_range", min: 0.1, max: 3, default: 1.0, step: 0.1 },
    ]},
    { id: 37, name: "Midpoint Displacement", params: [
      { name: "roughness", min: 0.1, max: 1.5, default: 0.5, step: 0.05 },
      { name: "num_layers", min: 1, max: 8, default: 3, step: 1 },
      { name: "threshold", min: 0.1, max: 0.9, default: 0.5, step: 0.05 },
    ]},
    { id: 38, name: "Island/Archipelago", params: [
      { name: "num_islands", min: 1, max: 15, default: 5, step: 1 },
      { name: "island_min_radius", min: 1, max: 8, default: 3, step: 1 },
      { name: "island_max_radius", min: 3, max: 15, default: 7, step: 1 },
      { name: "bridge_width", min: 1, max: 3, default: 1, step: 1 },
      { name: "fill_ratio", min: 0.1, max: 0.8, default: 0.4, step: 0.05 },
    ]},
    { id: 61, name: "River/Watershed", params: [
      { name: "num_drops", min: 50, max: 500, default: 200, step: 50 },
      { name: "noise_scale", min: 0.01, max: 0.2, default: 0.08, step: 0.01 },
      { name: "height_threshold", min: 0.1, max: 0.9, default: 0.5, step: 0.05 },
      { name: "river_width", min: 1, max: 3, default: 1, step: 1 },
      { name: "num_sources", min: 1, max: 15, default: 5, step: 1 },
    ]},
    { id: 62, name: "Crystal Growth", params: [
      { name: "num_seeds", min: 2, max: 20, default: 8, step: 1 },
      { name: "growth_steps", min: 20, max: 300, default: 100, step: 10 },
      { name: "axis_bias", min: 0.1, max: 1, default: 0.7, step: 0.05 },
      { name: "connect_chance", min: 0, max: 1, default: 0.8, step: 0.05 },
      { name: "min_crystal_size", min: 2, max: 10, default: 4, step: 1 },
    ]},
  ]},
  { name: "Pattern", algorithms: [
    { id: 5, name: "WFC", params: [
      { name: "max_retries", min: 1, max: 50, default: 10, step: 1 },
    ]},
    { id: 20, name: "Superimposition", params: [
      { name: "num_stamps", min: 5, max: 100, default: 40, step: 5 },
      { name: "rect_weight", min: 0, max: 10, default: 4, step: 1 },
      { name: "circle_weight", min: 0, max: 10, default: 2, step: 1 },
      { name: "corridor_h_weight", min: 0, max: 10, default: 3, step: 1 },
      { name: "corridor_v_weight", min: 0, max: 10, default: 3, step: 1 },
      { name: "stamp_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "stamp_max_size", min: 4, max: 15, default: 8, step: 1 },
      { name: "corridor_min_len", min: 2, max: 8, default: 4, step: 1 },
      { name: "corridor_max_len", min: 4, max: 20, default: 12, step: 1 },
    ]},
    { id: 42, name: "Herringbone Wang Tiles", params: [
      { name: "tile_size", min: 3, max: 12, default: 6, step: 1 },
      { name: "floor_ratio", min: 0.1, max: 0.9, default: 0.5, step: 0.05 },
      { name: "corridor_chance", min: 0, max: 1, default: 0.3, step: 0.05 },
    ]},
    { id: 43, name: "L-System", params: [
      { name: "iterations", min: 1, max: 8, default: 4, step: 1 },
      { name: "segment_length", min: 1, max: 5, default: 2, step: 1 },
      { name: "turn_angle", min: 1, max: 4, default: 2, step: 1 },
      { name: "room_chance", min: 0, max: 0.5, default: 0.15, step: 0.05 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 9, default: 5, step: 1 },
    ]},
    { id: 55, name: "Hex Grid", params: [
      { name: "hex_size", min: 2, max: 8, default: 4, step: 1 },
      { name: "open_chance", min: 0.2, max: 0.8, default: 0.5, step: 0.05 },
      { name: "extra_wall_chance", min: 0, max: 0.5, default: 0.2, step: 0.05 },
    ]},
    { id: 56, name: "City Block", params: [
      { name: "block_size", min: 3, max: 12, default: 6, step: 1 },
      { name: "street_width", min: 1, max: 3, default: 1, step: 1 },
      { name: "building_chance", min: 0.2, max: 1, default: 0.7, step: 0.05 },
      { name: "door_chance", min: 0, max: 1, default: 0.5, step: 0.05 },
      { name: "remove_street_chance", min: 0, max: 0.5, default: 0.15, step: 0.05 },
    ]},
    { id: 67, name: "Penrose Tiling", params: [
      { name: "num_lines", min: 2, max: 8, default: 4, step: 1 },
      { name: "floor_chance", min: 0.1, max: 0.9, default: 0.6, step: 0.05 },
      { name: "room_chance", min: 0, max: 0.5, default: 0.1, step: 0.05 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 8, default: 5, step: 1 },
    ]},
  ]},
  { name: "Hybrid", algorithms: [
    { id: 9, name: "Voronoi Region", params: [
      { name: "num_seeds", min: 3, max: 20, default: 8, step: 1 },
      { name: "shrink", min: 0, max: 3, default: 1, step: 1 },
      { name: "extra_edge_chance", min: 0, max: 1, default: 0.2, step: 0.05 },
    ]},
    { id: 12, name: "Radial", params: [
      { name: "num_rings", min: 2, max: 8, default: 4, step: 1 },
      { name: "sectors_per_ring", min: 4, max: 16, default: 8, step: 1 },
      { name: "ring_width", min: 2, max: 6, default: 3, step: 1 },
      { name: "spoke_chance", min: 0, max: 1, default: 0.6, step: 0.05 },
      { name: "gap_chance", min: 0, max: 1, default: 0.2, step: 0.05 },
    ]},
    { id: 29, name: "Space Colonization", params: [
      { name: "num_attractors", min: 20, max: 200, default: 80, step: 10 },
      { name: "kill_distance", min: 1, max: 5, default: 2, step: 1 },
      { name: "influence_distance", min: 5, max: 30, default: 15, step: 1 },
      { name: "step_size", min: 1, max: 3, default: 1, step: 1 },
      { name: "corridor_width", min: 1, max: 4, default: 1, step: 1 },
      { name: "room_chance", min: 0, max: 0.5, default: 0.15, step: 0.05 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 8, default: 5, step: 1 },
    ]},
    { id: 22, name: "Parametric Tunnelers", params: [
      { name: "num_tunnelers", min: 1, max: 8, default: 3, step: 1 },
      { name: "tunnel_length", min: 20, max: 200, default: 80, step: 10 },
      { name: "initial_width", min: 1, max: 4, default: 1, step: 1 },
      { name: "max_width", min: 1, max: 8, default: 4, step: 1 },
      { name: "turn_chance", min: 0, max: 1, default: 0.2, step: 0.05 },
      { name: "width_change_chance", min: 0, max: 0.5, default: 0.1, step: 0.05 },
      { name: "room_chance", min: 0, max: 0.3, default: 0.06, step: 0.02 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 12, default: 7, step: 1 },
    ]},
    { id: 51, name: "Platformer Level", params: [
      { name: "num_platforms", min: 5, max: 30, default: 15, step: 1 },
      { name: "platform_min_len", min: 2, max: 6, default: 3, step: 1 },
      { name: "platform_max_len", min: 4, max: 15, default: 8, step: 1 },
      { name: "ladder_chance", min: 0, max: 1, default: 0.3, step: 0.05 },
      { name: "gap_chance", min: 0, max: 0.5, default: 0.2, step: 0.05 },
      { name: "water_level", min: 0, max: 5, default: 2, step: 1 },
    ]},
    { id: 68, name: "Delaunay + Gabriel", params: [
      { name: "num_points", min: 5, max: 30, default: 15, step: 1 },
      { name: "room_min_size", min: 2, max: 6, default: 3, step: 1 },
      { name: "room_max_size", min: 3, max: 10, default: 6, step: 1 },
      { name: "corridor_width", min: 1, max: 3, default: 1, step: 1 },
      { name: "extra_edge_chance", min: 0, max: 0.5, default: 0.15, step: 0.05 },
    ]},
  ]},
  { name: "Hex", algorithms: [
    { id: 69, name: "Hex Maze", params: [
      { name: "cols", min: 8, max: 40, default: 20, step: 1 },
      { name: "rows", min: 8, max: 30, default: 15, step: 1 },
      { name: "room_chance", min: 0, max: 0.5, default: 0.15, step: 0.05 },
    ]},
    { id: 70, name: "Hex CA", params: [
      { name: "cols", min: 8, max: 40, default: 20, step: 1 },
      { name: "rows", min: 8, max: 30, default: 15, step: 1 },
      { name: "initial_fill", min: 0.1, max: 0.9, default: 0.45, step: 0.05 },
      { name: "iterations", min: 1, max: 20, default: 5, step: 1 },
      { name: "birth", min: 1, max: 6, default: 4, step: 1 },
      { name: "survival", min: 1, max: 6, default: 3, step: 1 },
    ]},
    { id: 71, name: "Hex Voronoi", params: [
      { name: "cols", min: 8, max: 40, default: 20, step: 1 },
      { name: "rows", min: 8, max: 30, default: 15, step: 1 },
      { name: "num_seeds", min: 2, max: 15, default: 6, step: 1 },
      { name: "shrink", min: 0, max: 3, default: 1, step: 1 },
    ]},
    { id: 72, name: "Hex WFC", params: [
      { name: "cols", min: 8, max: 40, default: 20, step: 1 },
      { name: "rows", min: 8, max: 30, default: 15, step: 1 },
      { name: "max_retries", min: 1, max: 50, default: 10, step: 1 },
    ]},
    { id: 73, name: "Hex Spiral", params: [
      { name: "cols", min: 8, max: 40, default: 20, step: 1 },
      { name: "rows", min: 8, max: 30, default: 15, step: 1 },
      { name: "spacing", min: 1, max: 5, default: 2, step: 1 },
      { name: "room_chance", min: 0, max: 0.5, default: 0.2, step: 0.05 },
    ]},
    { id: 74, name: "Hex Territory", params: [
      { name: "cols", min: 8, max: 40, default: 20, step: 1 },
      { name: "rows", min: 8, max: 30, default: 15, step: 1 },
      { name: "num_factions", min: 2, max: 8, default: 4, step: 1 },
      { name: "aggression", min: 0, max: 1, default: 0.3, step: 0.05 },
    ]},
  ]},
  { name: "3D", algorithms: [
    { id: 75, name: "Multi-Floor BSP", params: [
      { name: "depth", min: 2, max: 8, default: 3, step: 1 },
      { name: "min_room_size", min: 2, max: 10, default: 4, step: 1 },
      { name: "stair_count", min: 1, max: 8, default: 3, step: 1 },
    ]},
    { id: 76, name: "3D Drunkard", params: [
      { name: "depth", min: 2, max: 8, default: 3, step: 1 },
      { name: "fill_ratio", min: 0.1, max: 0.6, default: 0.35, step: 0.05 },
      { name: "climb_chance", min: 0, max: 0.5, default: 0.15, step: 0.05 },
    ]},
    { id: 77, name: "3D CA", params: [
      { name: "depth", min: 2, max: 8, default: 3, step: 1 },
      { name: "initial_fill", min: 0.1, max: 0.9, default: 0.45, step: 0.05 },
      { name: "iterations", min: 1, max: 20, default: 4, step: 1 },
      { name: "birth", min: 5, max: 20, default: 14, step: 1 },
      { name: "survival", min: 5, max: 20, default: 13, step: 1 },
    ]},
    { id: 78, name: "Vertical Shaft", params: [
      { name: "depth", min: 2, max: 8, default: 3, step: 1 },
      { name: "num_shafts", min: 1, max: 8, default: 3, step: 1 },
      { name: "room_chance", min: 0.1, max: 1, default: 0.5, step: 0.1 },
    ]},
    { id: 79, name: "Layered Caves", params: [
      { name: "depth", min: 2, max: 8, default: 3, step: 1 },
      { name: "connectivity", min: 0.1, max: 1, default: 0.3, step: 0.05 },
    ]},
    { id: 80, name: "3D Maze", params: [
      { name: "depth", min: 2, max: 8, default: 3, step: 1 },
      { name: "up_chance", min: 0, max: 0.5, default: 0.2, step: 0.05 },
    ]},
  ]},
  { name: "Quarter", algorithms: [
    { id: 81, name: "Isometric City", params: [
      { name: "max_height", min: 2, max: 12, default: 8, step: 1 },
      { name: "building_density", min: 0.2, max: 1, default: 0.7, step: 0.05 },
      { name: "street_width", min: 1, max: 4, default: 2, step: 1 },
    ]},
    { id: 82, name: "Cliff Dungeon", params: [
      { name: "max_height", min: 2, max: 10, default: 6, step: 1 },
      { name: "cliff_chance", min: 0, max: 1, default: 0.4, step: 0.05 },
      { name: "room_count", min: 3, max: 15, default: 8, step: 1 },
    ]},
    { id: 83, name: "Layered Plateau", params: [
      { name: "max_height", min: 2, max: 10, default: 6, step: 1 },
      { name: "num_plateaus", min: 2, max: 8, default: 4, step: 1 },
      { name: "erosion", min: 0, max: 1, default: 0.3, step: 0.05 },
    ]},
    { id: 84, name: "Castle Generator", params: [
      { name: "max_height", min: 2, max: 12, default: 8, step: 1 },
      { name: "tower_count", min: 2, max: 8, default: 4, step: 1 },
      { name: "wall_height", min: 1, max: 6, default: 3, step: 1 },
    ]},
    { id: 85, name: "Terraced Mines", params: [
      { name: "max_height", min: 2, max: 10, default: 6, step: 1 },
      { name: "num_terraces", min: 2, max: 8, default: 4, step: 1 },
      { name: "ore_chance", min: 0, max: 0.5, default: 0.1, step: 0.05 },
    ]},
    { id: 86, name: "Floating Islands", params: [
      { name: "max_height", min: 2, max: 12, default: 8, step: 1 },
      { name: "num_islands", min: 2, max: 10, default: 5, step: 1 },
      { name: "bridge_chance", min: 0, max: 1, default: 0.3, step: 0.05 },
    ]},
    { id: 87, name: "Ziggurat Temple", params: [
      { name: "max_height", min: 2, max: 12, default: 8, step: 1 },
      { name: "num_levels", min: 2, max: 8, default: 4, step: 1 },
      { name: "room_chance", min: 0, max: 1, default: 0.3, step: 0.05 },
    ]},
    { id: 88, name: "Canyon Ravine", params: [
      { name: "max_height", min: 2, max: 12, default: 8, step: 1 },
      { name: "canyon_width", min: 3, max: 12, default: 6, step: 1 },
      { name: "num_bridges", min: 1, max: 8, default: 3, step: 1 },
      { name: "cave_chance", min: 0, max: 1, default: 0.3, step: 0.05 },
    ]},
    { id: 89, name: "Harbor Town", params: [
      { name: "max_height", min: 2, max: 10, default: 6, step: 1 },
      { name: "water_ratio", min: 0.1, max: 0.6, default: 0.3, step: 0.05 },
      { name: "building_density", min: 0.1, max: 1, default: 0.6, step: 0.05 },
    ]},
    { id: 90, name: "Tower Dungeon", params: [
      { name: "max_height", min: 2, max: 12, default: 8, step: 1 },
      { name: "floors", min: 2, max: 8, default: 4, step: 1 },
      { name: "room_size", min: 2, max: 8, default: 4, step: 1 },
    ]},
    { id: 91, name: "Volcanic Crater", params: [
      { name: "max_height", min: 2, max: 12, default: 8, step: 1 },
      { name: "crater_ratio", min: 0.1, max: 0.6, default: 0.35, step: 0.05 },
      { name: "vent_chance", min: 0, max: 0.5, default: 0.2, step: 0.05 },
    ]},
    { id: 92, name: "Amphitheater", params: [
      { name: "max_height", min: 2, max: 10, default: 6, step: 1 },
      { name: "num_entrances", min: 2, max: 8, default: 4, step: 1 },
      { name: "arena_ratio", min: 0.1, max: 0.6, default: 0.3, step: 0.05 },
    ]},
  ]},
  { name: "Puzzle", algorithms: [
    { id: 99, name: "Sokoban Layout", params: [
      { name: "num_rooms", min: 2, max: 12, default: 6, step: 1 },
      { name: "blocks_per_room", min: 1, max: 6, default: 3, step: 1 },
    ]},
    { id: 100, name: "One-Way Gate", params: [
      { name: "num_rooms", min: 4, max: 20, default: 10, step: 1 },
      { name: "branch_factor", min: 1, max: 4, default: 2, step: 1 },
    ]},
    { id: 101, name: "Teleporter Maze", params: [
      { name: "num_clusters", min: 2, max: 8, default: 4, step: 1 },
      { name: "teleporters_per_cluster", min: 1, max: 4, default: 2, step: 1 },
    ]},
    { id: 102, name: "Lock Cascade", params: [
      { name: "chain_length", min: 2, max: 10, default: 6, step: 1 },
      { name: "side_room_chance", min: 0, max: 1, default: 0.3, step: 0.05 },
    ]},
    { id: 103, name: "Gravity Puzzle", params: [
      { name: "num_platforms", min: 4, max: 20, default: 10, step: 1 },
      { name: "inversion_y", min: 0.2, max: 0.8, default: 0.5, step: 0.05 },
    ]},
    { id: 104, name: "Mirror Dungeon", params: [
      { name: "num_rooms", min: 2, max: 10, default: 6, step: 1 },
      { name: "corruption", min: 0, max: 0.5, default: 0.15, step: 0.05 },
    ]},
  ]},
  { name: "Biome", algorithms: [
    { id: 93, name: "Continent", params: [
      { name: "land_ratio", min: 0.2, max: 0.8, default: 0.5, step: 0.05 },
      { name: "num_biomes", min: 2, max: 8, default: 4, step: 1 },
    ]},
    { id: 94, name: "Dungeon Ecosystem", params: [
      { name: "num_zones", min: 2, max: 6, default: 3, step: 1 },
      { name: "zone_size", min: 4, max: 15, default: 8, step: 1 },
    ]},
    { id: 95, name: "Seasonal Forest", params: [
      { name: "density_min", min: 0, max: 0.5, default: 0.1, step: 0.05 },
      { name: "density_max", min: 0.3, max: 1.0, default: 0.7, step: 0.05 },
      { name: "num_clearings", min: 1, max: 10, default: 5, step: 1 },
    ]},
    { id: 96, name: "Swamp Labyrinth", params: [
      { name: "water_ratio", min: 0.2, max: 0.7, default: 0.4, step: 0.05 },
      { name: "path_count", min: 1, max: 6, default: 3, step: 1 },
    ]},
    { id: 97, name: "Desert Oasis", params: [
      { name: "num_oases", min: 1, max: 10, default: 5, step: 1 },
      { name: "dune_density", min: 0, max: 0.5, default: 0.2, step: 0.05 },
    ]},
    { id: 98, name: "Tundra Outpost", params: [
      { name: "num_outposts", min: 2, max: 10, default: 6, step: 1 },
      { name: "tunnel_chance", min: 0.1, max: 1.0, default: 0.5, step: 0.05 },
    ]},
  ]},
  { name: "Hex+", algorithms: [
    { id: 105, name: "Hex River Delta", params: [
      { name: "cols", min: 10, max: 40, default: 25, step: 1 },
      { name: "rows", min: 10, max: 30, default: 20, step: 1 },
      { name: "num_sources", min: 1, max: 6, default: 3, step: 1 },
      { name: "branch_chance", min: 0.1, max: 0.8, default: 0.4, step: 0.05 },
    ]},
    { id: 106, name: "Hex Fortress", params: [
      { name: "cols", min: 10, max: 40, default: 25, step: 1 },
      { name: "rows", min: 10, max: 30, default: 20, step: 1 },
      { name: "num_walls", min: 1, max: 5, default: 3, step: 1 },
      { name: "gate_count", min: 1, max: 4, default: 2, step: 1 },
    ]},
    { id: 107, name: "Hex Biome", params: [
      { name: "cols", min: 10, max: 40, default: 25, step: 1 },
      { name: "rows", min: 10, max: 30, default: 20, step: 1 },
      { name: "num_regions", min: 3, max: 12, default: 6, step: 1 },
      { name: "road_chance", min: 0.1, max: 1.0, default: 0.5, step: 0.05 },
    ]},
    { id: 108, name: "Hex Snowflake", params: [
      { name: "cols", min: 15, max: 50, default: 30, step: 1 },
      { name: "rows", min: 15, max: 40, default: 25, step: 1 },
      { name: "depth", min: 1, max: 6, default: 4, step: 1 },
      { name: "branch_ratio", min: 0.3, max: 0.9, default: 0.6, step: 0.05 },
    ]},
  ]},
  { name: "3D+", algorithms: [
    { id: 109, name: "Underwater Base", params: [
      { name: "depth", min: 2, max: 6, default: 4, step: 1 },
      { name: "room_density", min: 0.2, max: 0.7, default: 0.4, step: 0.05 },
    ]},
    { id: 110, name: "Tree Roots", params: [
      { name: "depth", min: 2, max: 6, default: 4, step: 1 },
      { name: "branch_chance", min: 0.1, max: 0.7, default: 0.4, step: 0.05 },
    ]},
    { id: 111, name: "Ant Nest 3D", params: [
      { name: "depth", min: 2, max: 6, default: 4, step: 1 },
      { name: "num_entrances", min: 1, max: 6, default: 3, step: 1 },
      { name: "chamber_chance", min: 0.1, max: 0.6, default: 0.3, step: 0.05 },
    ]},
    { id: 112, name: "Space Station", params: [
      { name: "depth", min: 2, max: 5, default: 3, step: 1 },
      { name: "ring_width", min: 1, max: 5, default: 3, step: 1 },
      { name: "num_spokes", min: 3, max: 8, default: 6, step: 1 },
    ]},
  ]},
  { name: "Quarter+", algorithms: [
    { id: 113, name: "Aqueduct", params: [
      { name: "max_height", min: 4, max: 12, default: 8, step: 1 },
      { name: "num_arches", min: 3, max: 10, default: 6, step: 1 },
      { name: "terrain_roughness", min: 0.1, max: 0.6, default: 0.3, step: 0.05 },
    ]},
    { id: 114, name: "Treehouse Village", params: [
      { name: "max_height", min: 4, max: 12, default: 8, step: 1 },
      { name: "num_trees", min: 3, max: 15, default: 8, step: 1 },
      { name: "bridge_chance", min: 0.1, max: 1.0, default: 0.5, step: 0.05 },
    ]},
    { id: 115, name: "Mineshaft Elevator", params: [
      { name: "max_height", min: 4, max: 12, default: 8, step: 1 },
      { name: "num_levels", min: 2, max: 6, default: 4, step: 1 },
      { name: "tunnel_count", min: 2, max: 8, default: 4, step: 1 },
    ]},
    { id: 116, name: "Glacier", params: [
      { name: "max_height", min: 4, max: 12, default: 8, step: 1 },
      { name: "num_crevasses", min: 2, max: 10, default: 5, step: 1 },
      { name: "cave_chance", min: 0.1, max: 0.6, default: 0.3, step: 0.05 },
    ]},
  ]},
];

export const ALGORITHMS: AlgorithmDef[] = CATEGORIES.flatMap(cat =>
  cat.algorithms.map(a => ({ ...a, category: cat.name }))
);
